version: '3.8'

services:  # Service MySQL

  # Service Backend (GameBE)
  backend:
    build:
      context: ./GameBE  # Thư mục chứa mã nguồn backend
    container_name: game-backend
    ports:
      - "3910:3910"
    environment:
      DB_HOST: db-mysql
      DB_USER: khoansa
      DB_PASSWORD: XGame@2024
      DB_NAME: khoansa
    depends_on:
      - db-mysql
    networks:
      - app_network

  # Service Frontend (GameFE)
  frontend:
    build:
      context: ./GameFE  # Thư mục chứa mã nguồn frontend
    container_name: game-frontend
    ports:
      - "3911:80"
    # depends_on:
    #   - backend
    networks:
      - app_network

# Networks
networks:
  app_network:
    driver: bridge

# Volumes
volumes:
  505f069841354b97f3e28d886e3a7fb955b0e61e19bfed5a9e109ecad36aec76:
    external: true
