version: '3.8'

services:  # Service MySQL
  db-mysql:
    image: mysql:5.7.40
    container_name: db-mysql
    restart: always
    ports:
      - "3309:3306"  # ánh xạ cổng host 3308 tới cổng container 3306
    environment:
      MYSQL_ROOT_PASSWORD: XGame@2024
      MYSQL_DATABASE: khoansa
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  # Service Backend (GameBE)
  backend:
    build:
      context: ./GameBE  # Thư mục chứa mã nguồn backend
    container_name: game-backend
    ports:
      - "3910:3910"
    environment:
      DB_HOST: db-mysql
      DB_USER: root
      DB_PASSWORD: XGame@2024
      DB_NAME: khoansa
    depends_on:
      - db-mysql
    networks:
      - app_network

  # Service Frontend (GameFE)
  frontend:
    build:
      context: ./GameFE  # Thư mục chứa mã nguồn frontend
    container_name: game-frontend
    ports:
      - "3911:80"
    depends_on:
      - backend
    networks:
      - app_network

# Networks
networks:
  app_network:
    driver: bridge

volumes:
  db_data:
